name: Integration Testing
on:
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Sync new tags
        id: tags-sync
        uses: ./
        with:
          base-repository: mamoe/mirai
          head-repository: meowool/mirai
          patch-author: chachako
          patch-author-email: 58068445+chachako@users.noreply.github.com
          filter-tags: 'v[2-9]\.[1-9][2-9].*'

      - name: Print new tags
        run: |
          while read tag
          do
            echo $tag
          done < ${{ steps.tags-sync.outputs.new-tags-file }}

      - name: Print and remove synced branches
        run: |
          cd ${{ steps.tags-sync.inputs.cloned-path }}
          while read branch
          do
            echo $branch
            git push origin --delete $branch
          done < ${{ steps.tags-sync.outputs.synced-branches-file }}
