name: Integration Testing
on:
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Sync new tags
        uses: ./
        with:
          base-repository: gradle/gradle
          patch-author: chachako
          patch-author-email: 58068445+chachako@users.noreply.github.com
          filter-tags: 'v[7-9]\..*'

      - name: Print new tags
        run: echo ${{ steps.sync.outputs.new-tags }}