name: Integration Testing
on:
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Sync new tags
        id: tags-sync
        uses: ./
        with:
          base-repository: gradle/gradle
          patch-author: chachako
          patch-author-email: 58068445+chachako@users.noreply.github.com
          filter-tags: 'v[7-9]\..*'

      - name: Print new tags
        run: |
          while read tag
          do
          　　echo $tag
          done < ${{ steps.tags-sync.outputs.new-tags-file }}

      - name: Print synced branches
        run: |
          while read branch
          do
          　　echo $branch
          done < ${{ steps.tags-sync.outputs.synced-branches-file }}